#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
import agent

data = json.load(sys.stdin)

# For restoring earlier configs, you may set the original credentialSecret. Next startup the key is changed, and data re-encrypted
# use case restore of already running node-red instances 
node-red-credentialSecret = data.get("node-red-credentialSecret", "")

# 
if node-red-credentialSecret:
    agent.set_env("node-red-credentialSecret", node-red-credentialSecret)
