#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# test if the module is upgrading from postgres 13
if [[ "$PREV_POSTGRES_IMAGE" =~ 13\.[0-9]+ ]]; then
    systemctl --user restart node-red.service
else
    # the module is not upgrading from postgres 13 and might be not configured
    systemctl --user try-restart node-red.service
fi