#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read ns8-node-red configuration
#

import os
import sys
import json
import agent
import subprocess

# Prepare return variable
config = {}

config["host"] =  os.environ.get("TRAEFIK_HOST","")
config["http2https"] =  os.environ.get("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] =  os.environ.get("TRAEFIK_LETS_ENCRYPT") == "True"

# Dump the configuratio to stdou
json.dump(config, fp=sys.stdout)